### ISSUE TITLE
Keep Code Comments not working with /*

### ISSUE THREAD

**Issue by pablofmorales** [dassjosh/Plugin.Merge#17]
in the merge.json we have the  `Keep Code Comments": false`
this works perfectly when you use `//` for comments but when you do multi-line comments using `/* */` this is not treated properly 

I quite love this library and I know that you are not responsive on the issue section, but I just want to do my part :D

**Comment by dassjosh** [comment]
This has been fixed in v1.0.8. Might take a bit to reflect on nuget
